### ISSUE TITLE
Per Annum Absent in Other Currency

### ISSUE THREAD

**Issue by aniketm007** [ocs-iitd/portal-issues#11]
**Describe the bug**
Per Annum Text is absent when the Currency is chosen as Others by the recruiter

**To Reproduce**
1. In the new JNF, go to Salary Details. Then Select Currency as Others and write any Currency

**Expected behavior**
Per Annum will be absent in the final printable form of JNF which is present when you choose some other currency

**Comment by divyam227227** [comment]
In the currency text box itself, you are supposed to add "Per Annum" after currency to display it. Like "RUPIAH Per Annum" etc. As you can also see in the dropdown of currency, the per annum is mentioned already. Like "USD Per Annum". Please let me know if you want it to appear by default.

**Comment by aniketm007** [comment]
Add Per Annum as default in Others

**Comment by divyam227227** [comment]
Fixed.
"Per Annum" in jnf and "Per Month" in tnf will be added by default if not entered by the user.
