### ISSUE TITLE
Minimum CGPA column visibility

### ISSUE THREAD

**Issue by aniketm007** [ocs-iitd/portal-issues#12]
**Describe the bug**
Minimum CGPA column is visible when the recruiter adds a Min. CGPA and then deletes

**To Reproduce**
1. In the JNF, put a min. CGPA. Save it. Delete that Min. CGPA and Save it Again

**Expected behavior**
In the printable form of the JNF, Min. CGPA column is present(column is empty)

**Comment by nihar5733** [comment]
Solved
