### ISSUE TITLE
Eligibility Section Issues in JNF 

### ISSUE THREAD

**Issue by aniketm007** [ocs-iitd/portal-issues#13]
Eligibility:
a)If All depts are selected but not Ph.D., Doctor of Philosophy still gets incorporated.
b)If you select PhD column then it doesn't show Doctor of Philosophy in the Selected Dept
c)If you select all Duals, two of the Dual Degrees in CS Dept are not selected, one in Mechanical Dept is not selected
d)After selecting all depts, if I unselect and select a dept it doesn't get selected. For example, If I select all Depts and then unselect CH1 dept and then select it again it doesn't get selected as it doesn't appear in the Selected Departments below and also not in the portal JNF

**Comment by nihar5733** [comment]
- select all duals bug solved
- for PhD, there is only Doctor of Philosophy and no other, I will consult Anil for this but I think there is only yes/no option for PhD and nothing more as of this portal (No department code for specific PhD student. So if PhD is selected then all PhD students will be eligible irrespective of department
- working on select all depts bug

**Comment by neelpy** [comment]
Is this resolved?

**Comment by aniketm007** [comment]
First two bugs are still there but the rest are resolved. Try to show Doctor of Philosophy on when PhD is selected and not when All Departments are selected in the Selected Department Column

**Comment by anilkumarsingh1911** [comment]
issue solved. as per discussion with  @aniketm007  and @anilkumarsingh1911
