### ISSUE TITLE
Displaying Change after Saving CV

### ISSUE THREAD

**Issue by aniketm007** [ocs-iitd/portal-issues#15]
Rather than having whole CV refreshed and original template is displayed after making even minute changes, only the text can be refreshed keeping the template fixed. This means Inside of CV will refresh keeping template zoom and scroll fixed.
Eg. If I am editing the 2nd page and have scrolled down and zoomed on a particular section, after making any change say typing a word, the whole cv refreshes and goes to top and is zoomed out. If I want to look how a particular line is displayed, for each minor change, I will have to scroll and zoom to that part again and again which is bit inconvenient.

**Comment by neelpy** [comment]
I don't think I can implement that

**Comment by nihar5733** [comment]
Suggestion noted for future development
