### ISSUE TITLE
Lines Count

### ISSUE THREAD

**Issue by aniketm007** [ocs-iitd/portal-issues#16]
2.	A line count and total lines available can be given at the side or corner. When the size gets exceeded by more than 1 page, following happens.
![CV Error1](https://user-images.githubusercontent.com/34143869/83572844-eca94a00-a547-11ea-8603-7a9b456c70ed.jpg)

 
Rather than that, an error message while adding points can be given that “Please remove 3 lines as the space limit exceeded”, etc can be given.

**Comment by neelpy** [comment]
Number of lines is a bit problematic parameter due to variable space occupied by section titles and point/subpoint which use multiple lines.

However, I have fixed the overlapping bug, and also extra pages are being removed instead of marking them red.
