### ISSUE TITLE
Saving CV in a particular Slot

### ISSUE THREAD

**Issue by aniketm007** [ocs-iitd/portal-issues#17]
CV is not getting saved in any of the slots and the following error message comes

![image](https://user-images.githubusercontent.com/34143869/83572993-401b9800-a548-11ea-8851-2942a59c4b7a.png)

**Comment by anilkumarsingh1911** [comment]
i didn`t find any error at the time of creating CV and uploading documents 

![1Capture](https://user-images.githubusercontent.com/40019042/83838602-53309280-a717-11ea-9c08-938dd0f15b17.PNG)

**Comment by anilkumarsingh1911** [comment]
error solved
