### ISSUE TITLE
Manage Document Error

### ISSUE THREAD

**Issue by aniketm007** [ocs-iitd/portal-issues#18]
a.	When you check manage documents, the CV is showing is there which was tried to save earlier but is not opening. Error is coming “Failed to load pdf document”.
b.	While trying to edit the CV, again an error is coming:                           
“Error!

**Comment by anilkumarsingh1911** [comment]
no error found.

![1Capture](https://user-images.githubusercontent.com/40019042/83838698-968b0100-a717-11ea-8ee9-a212267d5f38.PNG)

**Comment by anilkumarsingh1911** [comment]
error solved
