### ISSUE TITLE
Bold/Italics Issue

### ISSUE THREAD

**Issue by aniketm007** [ocs-iitd/portal-issues#19]
Following thing happens when bold or italics are tried for the text. For example, in following cases, following bug comes.
  
![image](https://user-images.githubusercontent.com/34143869/83573228-a86a7980-a548-11ea-9c9a-63f21e9a8eca.png)
![image](https://user-images.githubusercontent.com/34143869/83573242-ac969700-a548-11ea-851c-d93077657dd9.png)

**Comment by neelpy** [comment]
You cant use any other formatting inside the hyperlink format. Try putting anything outside the whole _text == link _
