### ISSUE TITLE
Extending Hyperling using a '$'

### ISSUE THREAD

**Issue by aniketm007** [ocs-iitd/portal-issues#20]
If ‘$’ is put end the end then even though the hyperlink is hidden, $ still reads it and rather than stretching the line till the margin, it compresses it instead as shown below merging the words. Thus in place of this, the “Codeforces Handle” should stretch till end.

![image](https://user-images.githubusercontent.com/34143869/83573350-e7003400-a548-11ea-989b-08b63ba4fdd1.png)
![image](https://user-images.githubusercontent.com/34143869/83573356-eb2c5180-a548-11ea-846c-18a3d3e2b5fb.png)

**Comment by neelpy** [comment]
Fixed

**Comment by neelpy** [comment]
One more bug fixed, the hyperlink feature is not available for btech and dual students
