### ISSUE TITLE
New Table in Statistics

### ISSUE THREAD

**Issue by anilkumarsingh1911** [ocs-iitd/portal-issues#21]
**Is your feature request related to a problem? Please describe.**
yes. most of the time we need all data at a glance for RTI.

**Describe the solution you'd like**
create a new table the contains all data of selected and accepted students.

**Additional context**
this new table is same as student statistical data with new columns, and change in existing query.

**Comment by neelpy** [comment]
Do you mean student page with all years' data?

**Comment by divyam227227** [comment]
The staff basically wants to have a table with all the details which is required in case a RTI is filed. It includes total number of offers (Accepted+Selected) along with other details like profile code and other student details.

**Comment by neelpy** [comment]
We can modify the current student table to include their requirements.

**Comment by divyam227227** [comment]
There was a small problem in the filter in the stats component. I fixed it. It may be required in other components also. Rest Anil Sir will look into what all columns must be added in the student stats table itself.

**Comment by anilkumarsingh1911** [comment]
master table created
