### ISSUE TITLE
new column in department selection

### ISSUE THREAD

**Issue by anilkumarsingh1911** [ocs-iitd/portal-issues#22]
add a new column in stat table:

stat > placement/training > department selection > ungrouped

https://tnp.iitd.ac.in/portal/admin/stats?key=dept_selections_ungrouped&type=placement

Ex:
BB1 -> BTECH
EE1 -> BTECH
MT6 -> DUAL
CS5 -> DUAL
AMA -> MTECH

**Comment by divyam227227** [comment]
Fixed.
