### ISSUE TITLE
Order of Eligible Departments

### ISSUE THREAD

**Issue by abhinav2342000** [ocs-iitd/portal-issues#23]
When a company adds a new branch in eligible departments section(The JNF was filled once and was showing to students, but new branches were added later), the new branches are coming at the end and this Jumbles out the order of branches.

**Expected behavior**
The branches should come in specific order always(Alphabetically). E.g. In the image, Biotech should come at the beginning before Civil. 

**Screenshots**
![WhatsApp Image 2020-06-09 at 5 00 13 AM](https://user-images.githubusercontent.com/45708416/84090102-6771d980-aa0e-11ea-8bcd-ac4d5bcb59e3.jpeg)

**Comment by divyam227227** [comment]
Fixed.
