### ISSUE TITLE
Advance rank not visible 

### ISSUE THREAD

**Issue by abhinav2342000** [ocs-iitd/portal-issues#24]
The JEE Advanced rank is not visible to anyone (student/company).

![WhatsApp Image 2020-06-09 at 5 16 06 AM](https://user-images.githubusercontent.com/45708416/84090800-5b871700-aa10-11ea-86f2-afd3ddd352d0.jpeg)

**Comment by divyam227227** [comment]
![Screenshot from 2020-06-20 23-25-42](https://user-images.githubusercontent.com/46631482/85208379-84cb6f80-b34d-11ea-951b-302ccdfca517.png)
The JEE Adv rank is visible in my case. In your case, it must've been absent in the database itself.
