### ISSUE TITLE
Different formats of Date of Birth

### ISSUE THREAD

**Issue by abhinav2342000** [ocs-iitd/portal-issues#25]
Date of Birth is showing in different formats for different students on company portal(The students also don't have any editing rights over that). 

E.g For some its: 1999-06-07 and for someone else its: 06-07-1999

**Comment by divyam227227** [comment]
Where exactly in company profile?

**Comment by neelpy** [comment]
@abhinav2342000 Please reply

**Comment by abhinav2342000** [comment]
> Where exactly in company portal?

It will not show up if not enabled in staff portal. Which company are you testing? We enabled the option for some specefic company while testing.

**Comment by divyam227227** [comment]
The DOB of students is fetched from student data only. So the DOB will occur in the format in which it was entered while entering student data. It must have been entered in different formats for different students when you were testing. In my case, it seems to come fine.
![Screenshot from 2020-07-24 22-03-04](https://user-images.githubusercontent.com/46631482/88414285-3a308d80-cdfa-11ea-9703-7d95a29d5134.png)
