### ISSUE TITLE
updates in 'place of posting' area 

### ISSUE THREAD

**Issue by anilkumarsingh1911** [ocs-iitd/portal-issues#29]
**Describe the bug**

**To Reproduce**
1. Go to  jnf/tnf-> 2) job details-> place of posting
2. add drop down button for country india or other,, if other open text box
3. just like currency

**Expected behavior**
we want job location for student, not the company origin location

**Comment by divyam227227** [comment]
Shouldn't place of posting be a city rather than a country? I think that having the place of posting for an intern as "Bengaluru" will be more useful than just "India".

**Comment by anilkumarsingh1911** [comment]
place of posting updated in jnf. @divyam227227 also update in tnf

**Comment by neelpy** [comment]
Is it resolved?

**Comment by anilkumarsingh1911** [comment]
Not now.

**Comment by anilkumarsingh1911** [comment]
solved
