### ISSUE TITLE
Courses Done functionality in CV 

### ISSUE THREAD

**Issue by ayushchoubey03** [ocs-iitd/portal-issues#32]
**bug**
Once the Courses Done section is switched on ( Page 2) , data gets displayed on page 2 but generates an error message on saving.
So this CV can't be viewed in Manage Documents Tab on the portal.

**Comment by neelpy** [comment]
How can I reproduce this?

**Comment by ayushchoubey03** [comment]
Couldn't understand. 
Basically the CV is not getting saved when we add the " Courses Done " section. 
Got it?

**Comment by neelpy** [comment]
Thanks, it is fixed.
