### ISSUE TITLE
CV guideliness

### ISSUE THREAD

**Issue by ayushchoubey03** [ocs-iitd/portal-issues#34]
**Bug**
How to use different bullets, not mentioned in guidelines 

**Screenshot**
![image](https://user-images.githubusercontent.com/67980213/86841449-92a92080-c0c1-11ea-8a31-27167616d87d.png)

**Comment by neelpy** [comment]
You can simply copy-paste them

**Comment by ayushchoubey03** [comment]
Ok, mention it in the guidelines, as people might not understand this
