### ISSUE TITLE
Company reg. site

### ISSUE THREAD

**Issue by ayushchoubey03** [ocs-iitd/portal-issues#35]
**Describe the bug**
The site is not working properly. After filling the information, we get the following problems, as attached in the screenshots :
1. No mail gets sent to the email id of HR.
2. The internship option is disabled.
3. This message gets displayed when clicked on submit

**Screenshots**

![tp1](https://user-images.githubusercontent.com/67980213/87232888-293a5200-c3e0-11ea-982d-72feaae52f2d.PNG)
![tp2](https://user-images.githubusercontent.com/67980213/87232893-2d666f80-c3e0-11ea-9168-e5d1b7306b40.PNG)
![WhatsApp Image 2020-07-11 at 5 34 25 PM](https://user-images.githubusercontent.com/67980213/87232980-ed53bc80-c3e0-11ea-9d77-45eec11aa2b9.jpeg)

**Comment by neelpy** [comment]
It is disabled because your email address is already registered with a training/placement profile.

**Comment by ayushchoubey03** [comment]
Ok, please check other queries too.

**Comment by neelpy** [comment]
Fixed.
