### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by mansi-web** [ocs-iitd/portal-issues#37]
Scroll bar does not work on the editor pane. For more flexible and easier addition of new points, a scroll bar would be beneficial.
[issue 2.docx](https://github.com/ocs-iitd/portal-issues/files/4908320/issue.2.docx)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by neelpy** [comment]
Please add the issue in proper format

**Comment by ayushchoubey03** [comment]
**Bug** 
Scroll bar does not work on the editor pane, its very difficult to add new points, as can be seen from the screenshot. The scroll bar at the right only scrolls the cv preview and not the editor. The editor only scrolls using up and down arrow keys which is a little troublesome. 

**Screenshot**
![image](https://user-images.githubusercontent.com/67980213/87563209-97329200-c6dc-11ea-8e1d-db654a4b5938.png)

**Alternatives**
For more flexible and easier addition of new points, a scroll bar would be beneficial for the editor side.

**Comment by neelpy** [comment]
Fixed
