### ISSUE TITLE
For interdisciplinary branches

### ISSUE THREAD

**Issue by mansi-web** [ocs-iitd/portal-issues#38]
![image](https://user-images.githubusercontent.com/29701783/87544773-a279c380-c6c4-11ea-90cc-f1db5383d28b.png)

For interdisciplinary departments which usually get ignored by the companies during program selection process, we can show them as a pop up in their sister branch. 
For example: when a company selects energy studies dept, a pop up recommendation should show up saying “people who select this also select MTech in Energy studies in interdisciplinary section”
Similarly, when a company selects MTech in chemical engineering dept, a pop up should appear guiding them to select “MTech in Polymer Science and Technology” as well. 
And they can select if it they wish to. With the pop up appearing at the time of selecting allied branch, we can make sure that they definitely are aware of the interdisciplinary programs.
Presently, the pop up just appears in the interdisciplinary section. A company may or may not visit it. Hence, the uncertainty.

**Comment by anilkumarsingh1911** [comment]
Please write the text

**Comment by ayushchoubey03** [comment]
I will add a new issue. Close this issue.

**Comment by neelpy** [comment]
Okay
