### ISSUE TITLE
Departments not getting ticked

### ISSUE THREAD

**Issue by ayushchoubey03** [ocs-iitd/portal-issues#40]
* Bug* 
The following departments could not be selected in JNF while filling/editing : 

M.Tech. in Materials Engineering ( Material Science and Engg. )
M.Tech. in Renewable Energy Technologies and Management ( Energy Studies )
M.Tech. in Energy & Environment Technologies and Management ( Energy Studies )
All M.S.(R) departments

**Comment by anilkumarsingh1911** [comment]
Solved

**Comment by anilkumarsingh1911** [comment]
Solved
