### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by ayushchoubey03** [ocs-iitd/portal-issues#43]
**Is your feature request related to a problem? Please describe.**
In the personal notification --> Departments, the Fetch button works pretty good but when the wrong profile code is searched, it takes long time. 

**Describe the solution you'd like**
The profile code is usually, an alphabet and 4-number code. If the input is not like that, display wrong code entered.
Else use the algorithm you have used for  personal notification --> Additional Students which displays wrong entry no. almost instantly.

**Comment by neelpy** [comment]
Fixed
