### ISSUE TITLE
Release v1.0 Bugs

### ISSUE THREAD

**Issue by neelpy** [ocs-iitd/portal-issues#46]
- [x] Policy Links
- [ ] Register mail not sent
- [x] Links on register page
- [x] Manage mails and Archive permissions not set (disabled for coordi login)
- [ ] Admin login reforms
- [x] Add indicator for personalized notifs
- [x] Add links to mobile apps on Notices and Notifs
- [x] In Archive Profiles, link to JNF/TNF not working
- [x] In Archive training students section, add intern date column
- [x] Set mail limit (1000 per hour)
- [x] Create separate mail template categories training and placement for company (set password)
- [x] Prepare onroll table
- [x] JNF eligibility issues
- [x] Sync db structures
- [x] Modify procedure page in the website
- [ ] Tentative schedule link
- [ ] mobile-app production release
- [x] Remove Subject and Content from Mail log table columns

**Comment by anilkumarsingh1911** [comment]
clicking on profile Details not working properly

https://tnp.iitd.ac.in/portal/admin/archive

**Comment by anilkumarsingh1911** [comment]
in archive profile, training area, student section, intern date is not visible. 
intern date is important for training area.

**Comment by ayushchoubey03** [comment]
Small bugs and feature : 
1. NF : Add a small note at the top of JNF saying " All star marked fields have to be compulsorily fixed " 
2. Calendar : Disable old dates in Date of Joining in NF.

**Comment by ayushchoubey03** [comment]
**Bug** 
The following depts. are not visible in the printable version ( Highlighted )

![Capture1](https://user-images.githubusercontent.com/67980213/88918510-2b792900-d287-11ea-9d73-26d6e46bc80b.PNG)

![2020-07-30 (3)](https://user-images.githubusercontent.com/67980213/88918570-4b105180-d287-11ea-89db-92d481bb9ed3.png)

**Comment by anilkumarsingh1911** [comment]
We have fix some bugs. Try to login in beta portal. And fill jnf again.

**Comment by anilkumarsingh1911** [comment]
Set Max e-mail limit 999 for 1 hour. As per discussion with pradeep sir

**Comment by anilkumarsingh1911** [comment]
> **Bug** 
> The following depts. are not visible in the printable version ( Highlighted )
> 
> ![Capture1](https://user-images.githubusercontent.com/67980213/88918510-2b792900-d287-11ea-9d73-26d6e46bc80b.PNG)
> 
> ![2020-07-30 (3)](https://user-images.githubusercontent.com/67980213/88918570-4b105180-d287-11ea-89db-92d481bb9ed3.png)
> 


Open beta portal.

**Comment by anilkumarsingh1911** [comment]
> > **Bug** 
> > The following depts. are not visible in the printable version ( Highlighted )
> > 
> > ![Capture1](https://user-images.githubusercontent.com/67980213/88918510-2b792900-d287-11ea-9d73-26d6e46bc80b.PNG)
> > 
> > ![2020-07-30 (3)](https://user-images.githubusercontent.com/67980213/88918570-4b105180-d287-11ea-89db-92d481bb9ed3.png)
> > 
> 
> 
> Open beta portal.

Beta portal version 1.1
Updated on 29 July 2020

**Comment by anilkumarsingh1911** [comment]
in manage mails

https://tnp.iitd.ac.in/beta/portal/admin/manage-mails

in select column area, if we select subject or content, then whole table disappear
![Capture](https://user-images.githubusercontent.com/40019042/89029509-3f3a9300-d34c-11ea-9dd6-18f7f39d5fdf.PNG)

**Comment by anilkumarsingh1911** [comment]
in the current system, a student can create cv without uploading image. 
and that is invalid in prev system

**Comment by anilkumarsingh1911** [comment]
if deadline in not set for cv, then student are creating cv.

**Comment by anilkumarsingh1911** [comment]
> **Bug**
> The following depts. are not visible in the printable version ( Highlighted )
> 
> ![Capture1](https://user-images.githubusercontent.com/67980213/88918510-2b792900-d287-11ea-9d73-26d6e46bc80b.PNG)
> 
> ![2020-07-30 (3)](https://user-images.githubusercontent.com/67980213/88918570-4b105180-d287-11ea-89db-92d481bb9ed3.png)

..
fixed. check in portal
