### ISSUE TITLE
EWS & PH category

### ISSUE THREAD

**Issue by anilkumarsingh1911** [ocs-iitd/portal-issues#51]
**Is your feature request related to a problem? Please describe.**
psu need ews and ph category student data

**Describe the solution you'd like**
add columns in database for ews and ph

**Additional context**
ews and ph column should be in "bit" datatype

**Comment by anilkumarsingh1911** [comment]
show all admin persons, as discussed with Anishya Mam

**Comment by anilkumarsingh1911** [comment]
but don`t show on faculty and nucleus login

**Comment by divyam227227** [comment]
For this, I suppose we need to add new columns in database itself. As suggested by you a few days back, you asked to not do such changes now. Should I do this now?

**Comment by anilkumarsingh1911** [comment]
Column already exist. Category

**Comment by anilkumarsingh1911** [comment]
column added, in category branch
