### ISSUE TITLE
facilities and company address

### ISSUE THREAD

**Issue by mansiocs231219** [ocs-iitd/portal-issues#59]
**Is your feature request related to a problem? Please describe.**
we need these column in tables, 

https://tnp.iitd.ac.in/portal/admin/stats?key=student_allData&type=training

https://tnp.iitd.ac.in/portal/admin/stats?key=student_stats&type=training

**Describe the solution you'd like**
add these columns.

**Comment by divyam227227** [comment]
I do not have login credentials for admin login. Could you please post screenshots?

**Comment by anilkumarsingh1911** [comment]
resolved, in deadline branch
