### ISSUE TITLE
Revoke Applications Feature

### ISSUE THREAD

**Issue by Utki01** [ocs-iitd/portal-issues#7]
**Revoke Applications of Students from JNF/TNF**
OCS should be able to revoke applications from a particular profile if it decides to not visit campus for recruitment. In some scenarios, applications of a particular branch/course need to be revoked if it was ineligible/made ineligible by the recruiter.

**Description**
-> Requirement: One feature to revoke all applications in current view (Revoke All in Current View)
-> Access: Only staff, HOD logins have access. Access should not be provided to coordinator logins
-> Functionality: Applications revoked disappear from company and admin portals. Application count of the candidates decreases by 1

**Comment by anilkumarsingh1911** [comment]
if u upload csv with entrynumber, status then it will update the status.
ex; 2013cs50291,Not Applied
and that feature is already is in the system
